### ISSUE TITLE
Car Details Page - Find Workshop Near Me

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#10]
name: Car Details Page - Find Workshop Near Me
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to find workshops near me
**in order to** get my car fixed / make an appointment.

# Description

![Car Details Page](https://user-images.githubusercontent.com/10528055/167129446-17b8c253-9d92-4e8b-827a-eab34bcf426e.png)

# Acceptance Criteria

- [ ] MVP --> open Google Maps with user location
- [ ] enter my location into input fields / search bar

# Tasks

(for developers team)

- [ ] pass location info to google maps link
- [ ] open google maps in new tab (https://developers.google.com/maps/documentation/urls/get-started)

# Complexity
S
