### ISSUE TITLE
Advanced NavBar - Gas Station Scanner

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#11]
name: Advanced NavBar - Gas Station Scanner
about:
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to have the option to scan local gas stations
**in order to** to check prices and opening hours (open / closed).

# Description

![Advanced NavBar_Gas Station Scanner](https://user-images.githubusercontent.com/10528055/167137285-301771af-a86a-4bc9-b2b2-f479fe71ee2d.png)

# Acceptance Criteria

- [ ] Select fuel type
- [ ] view list of gas stations within a 50km radius

# Tasks

(for developers team)

- [ ] connect to API (https://creativecommons.tankerkoenig.de/)
- [ ] post and get requested data based on user location
- [ ] render gas station cards in frontend from API call

# Complexity
L
