### ISSUE TITLE
Advanced Feature - Generate KM-Standszertifikat

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#12]
name: Advanced Feature - Generate KM-Standszertifikat
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to generate a KM-Standszertifikat based on my car data
**in order to** create a trusted certificate in case I want to sell my car.

# Description

generate a PDF from most up to date car data

# Acceptance Criteria

- [ ] Select Certificate
- [ ] Generate Certificate
- [ ] Receive Certificate via Email in PDF format

# Tasks

(for developers team)

- [ ] derive info from latest car data
- [ ] generate PDF with time stamp
- [ ] send to user via email

# Complexity
L
