### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#13]
name: Login Page
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to login to my caars account
**in order to** to view my personal data and car profiles.

# Description

![Login_Social Login](https://user-images.githubusercontent.com/10528055/167138583-6a781c93-9b31-46d5-a422-3bc63654337b.png)

# Acceptance Criteria

- [ ] Login with social accounts
- [ ] Access my user profile and cars

# Tasks

(for developers team)

- [ ] implement NextAuth.js
- [ ] Build session based content rendering / access
- [ ] protect API routes

# Complexity
XL
