### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#14]
name: Register Page
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to register at caars with email and password
**in order to** create my personal account.

# Description

![Register User Page](https://user-images.githubusercontent.com/10528055/167139419-af495250-ba94-474f-8735-d5f051d4eae8.png)

# Acceptance Criteria

- [ ] Register with email
- [ ] double password verification
- [ ] - [ ] accept terms and conditions (mandatory)
- [ ] receive activation email

# Tasks

(for developers team)

- [ ] build Registration form and pass data to db
- [ ] implement with NextAuth.js Login for user signin
- [ ] Store user data in db
- [ ] hash user info in URL
- [ ] send activation email

https://jasonwatmore.com/post/2021/08/19/next-js-11-user-registration-and-login-tutorial-with-example-app

# Complexity
XL
