### ISSUE TITLE
Add DatePicker "Zulassungsdatum"

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#15]
name: Add DatePicker "Zulassungsdatum"
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to set the "Zulassungdatum" for a specific vehicle in the Car'sDetail Page
**in order to** to store the date and later aggregate further car data based on the date.

# Description

! Split from https://github.com/StelzenPieper/capstone-project/issues/1 !
To be added as a date picker within the car details page.

# Acceptance Criteria

- [ ] view date picker with label "Zulassungsdatum"
- [ ] pick date
- [ ] dave date to car data (local storage)

# Tasks

(for developers team)

- [ ] input type date
- [ ] store to local storage with persist/zustand

# Complexity
S
