### ISSUE TITLE
Upload functionality for "Fahrzeugschein"

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#16]
name: Upload functionality for "Fahrzeugschein"
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to upload and store my "Fahrzeugschein" within a specified car details profile
**in order to** access the img in the app (later OCR data from img)

# Description

! Split from [Upload functionality for "Fahrzeugschein"](https://github.com/StelzenPieper/capstone-project/issues/1) 
Upload Fahrzeugschein and store in db (e.g. cloudinary)

# Acceptance Criteria

- [ ] upload option for Fahrzeugschein
- [ ] select img
- [ ] upload img
- [ ] view img in car details page
- [ ] edit img (overwrite with another img)
- [ ] delete img

# Tasks

(for developers team)

- [ ] upload button
- [ ] img selector from device
- [ ] store img to cloudinary (or other db)
- [ ] render img in car details page on click
- [ ] edit (reupload img)
- [ ] delete img

# Complexity
L
