### ISSUE TITLE
 info-overlay to display additional info where to find required details on "Fahrzeugschein"

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#17]
name:  info-overlay to display additional info where to find required details on "Fahrzeugschein"
about:
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to know where to find my VIN on my Fahrzeugschein
**in order to** to enter it into the "add car" form.

# Description

!Split from https://github.com/StelzenPieper/capstone-project/issues/1!
[Add new Car_caars](https://user-images.githubusercontent.com/10528055/168234414-a81384f6-6968-424c-b396-6a32d143367c.png)

# Acceptance Criteria

- [ ] click on info "i"
- [ ] open info box
- [ ] view img within and where to find VIN on "Fahrzeugschein"
- [ ] close info box

# Tasks

(for developers team)

- [ ] info "i" button
- [ ] open modal on click
- [ ] render img and hint
- [ ] close button

# Complexity
S
