### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#18]
name: Profile Page
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to view my profile page
**in order to** to edit & view data.

# Description

Simple user profile page with input / store of:
- First Name, Last Name
- Date of Birth
- Address
- Profile Img

# Acceptance Criteria

- [ ] view profile page
- [ ] edit / view data
- [ ] store data (local/db)
- [ ] upload profile img

# Tasks

(for developers team)

- [ ] create profile page
- [ ] create input field to edit data
- [ ] upload img
- [ ] store img in db (cloudinary)

# Complexity
L
