### ISSUE TITLE
Handle invalid / miss-typed VINs

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#19]
name: Handle invalid / miss-typed VINs
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** have to be notified, if my VIN cannot be found
**in order to** to manually check if misspelled. 

# Description

fetch VIN data from API
error message displayed to user if no data is returned
"VIN kann nicht gefunden werden. Bitte überprüfen Sie Ihre Eingabe"

# Acceptance Criteria

- [x] display error message if no data is returned
- [x] "VIN kann nicht gefunden werden. Bitte überprüfen Sie Ihre Eingabe"

# Tasks

(for developers team)

- [x] check return from API if valid
- [x] if no data returned (invalid) display error message: "VIN kann nicht gefunden werden. Bitte überprüfen Sie Ihre Eingabe

# Complexity
M
