### ISSUE TITLE
Create User Dashboard

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#2]
name: Create User Dashboard
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to view my personal dashboard when accessing the app
**in order to** display the options I have within.

# Description

![UserDashboard_no cars](https://user-images.githubusercontent.com/10528055/166935143-cbc54969-de89-4671-b496-cfab78856d6a.png)

# Acceptance Criteria

- [x] When starting the app I first am shown my dashboard
- [x] displays logo top left of header element
- [x] displays user profile in top right of header element
- [x] displays navbar on bottom of screen
- [x] displays "Add Car"-Button in middle of screen ((US: https://github.com/StelzenPieper/capstone-project/issues/1#issue-1226401752)

# Tasks

(for developers team)

- [x] Create header component
- [x] Add logo
- [x] Add User-Profile component
- [x] Create navbar component in Footer
- [x] Setup routes where applicable

# Complexity
S

**Comment by CJAkkuec** [comment]
Very nice! You could probably just call this "User Dashboard", to avoid confusion regarding the 'create'. The implication here (if you're being outrageously strict) would be that the user would have the ability to create their own user dashboard. ;)

Sidenote: "Create navbar component in Footer" <- a navbar is a navbar regardless of where it is. It is never a footer. [A footer is its own thing entirely.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer) Oftentimes people will use the` <footer>` tag for a navbar that is predominantly displayed at the bottom of the screen. That is semantically wrong.
