### ISSUE TITLE
Bookmark favorite car

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#22]
name: Bookmark favorite car

# Value Proposition

**As a** USER
**I have** to be able to bookmark my favorite car if I have multiple listed
**in order to** to have a quick access.

# Description

![Card Component_car](https://user-images.githubusercontent.com/10528055/166939795-7844f7ff-f49f-42b8-bb16-98613fc23d44.png)

# Acceptance Criteria

- [x] click "bookmark"-button

- [x] repeatedly clicking on the "bookmark"-button toggles the functionality on and off

# Tasks

(for developers team)

- [x] create toggle/untoggle function

# Complexity
M
