### ISSUE TITLE
Image Slider

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#23]
name: Image Slider
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to view multiple images in a slider element
**in order to** have access to the images in a single space.

# Description

Image Slider component that will display multiple images with a simple navigation inside slider

# Acceptance Criteria

- [x] View multiple images in slider
- [x] navigate slider left / right to view next / previous image

# Tasks

(for developers team)

- [x] build slider component
- [x] include navigation of images in slider
- [x] load images from db (cloudinary)

# Complexity
L
