### ISSUE TITLE
Create Filter Toggle

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#24]
name: Create Filter Toggle

# Value Proposition

**As a** USER
**I have** to be able to toggle the view of my cars added
**in order to** to view only favorite ones or show all.

# Description

toggle button to toggle filter on and off

# Acceptance Criteria

- [x] default: show all my added cars
- [x] on toggle only view my favorite cars
- [x] if a car is marked as favorite show on top of list in the "view all" view
- [x] if on the view favorite only view and a vehicle is untoggled as favorite remove from list

# Tasks

(for developers team)

- [x] add toggle button component 
- [x] filter by favorite= true & favorite = false
- [x] render Cards based on filter toggle
- [x] move vehicles marked as "favorite" on top of list in the view all view
- [x] remove vehicle from favorite list if favorite is untoggled

# Complexity
M
