### ISSUE TITLE
Create Card-Component (Car)

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#3]
name: Create Card-Component (Car)

# Value Proposition

**As a** USER
**I have** to be able to view my setup cars within my dashboard
**in order to** access the car's details page.     

# Description

![Card Component_car](https://user-images.githubusercontent.com/10528055/166939795-7844f7ff-f49f-42b8-bb16-98613fc23d44.png)

# Acceptance Criteria

- [x] Display the car's model name
- [x] Display the car's vin number
- [ ] Toggle as favorite / untoggle as favorite --> moved to separate US: https://github.com/StelzenPieper/capstone-project/issues/22
- [ ] Display car's mileage from data (if available)
- [ ] Display option to delete/remove car
- [ ] functionality to delete/remove car works accordingly
- [ ] Display car images with slider option (if image is available) --> moved to separate US: https://github.com/StelzenPieper/capstone-project/issues/23
- [ ] On click navigate to car's details page (specified in different user story)

# Tasks

(for developers team)

- [ ] create card component for single or multiple cars (map)
- [ ] GET car details from car data in caars' db (model, Kilometerstand, vin, images)
- [ ] display delete button
- [ ] create delete function to remove car from profile

# Complexity
M

**Comment by HishamAlmannai** [comment]
I have to be able to view my setup "of?" cars within my dashboard

Kilometerstand = mileage

Since there are a lot of features in this UserStory you could maybe rethink the scope of this userstory.

create toggle/untoggle function and display card in order accordingly 
For bookmark? What does display accordingly mean? Is there a sorting/filter of any kind?

On click navigate to car's details page
Is a detail page done already? Link to UserStory please.

Any tests?

**Comment by sebastianottow** [comment]
Hi Hisham,
thanks for the review I included your feedback accordingly.
Please review again.
Thanks,
Sebastian :)

**Comment by HishamAlmannai** [comment]
Hi Sebastian,
very nice. I would have still one detail:

Acceptance Criteria
Display option to delete/remove car

vs.

Tasks
create delete function

I think display  and function is different ;)
But nevertheless approved

**Comment by sebastianottow** [comment]
Hi Hisham,

thanks for the approval. I adjusted the US according to your last comment :)
