### ISSUE TITLE
Render Card List (Car)

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#4]
name: Render Card List (Car)
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to view all my added cars in my dashboard
**in order to** access each car's details page.

# Description

![Render Card List_car](https://user-images.githubusercontent.com/10528055/166943677-f5b84ef5-ca99-4588-8ffd-7bfd06147690.png)

# Acceptance Criteria

- [x] Display all setup cars as cards listed one after the other
- [x] Display favorite cars (descending order favorite > not-favorite) --> moved to individual story: https://github.com/StelzenPieper/capstone-project/issues/22

# Tasks

(for developers team)

- [x] create map function to display all cars in individual cards
- [x] create a function to display favorite cars in descending oder (favorite to not-favorite) --> moved to new story
- [x] un-/toggle favorite will rerender the list's order --> moved to new story

# Complexity
M

**Comment by irenepapaspyratos** [comment]
Suggestion:
- Display favorite cars (descending order favorite > not-favorite) => Display favorite cars first
just in case you don't have a real rating
- the toggle-task could be specified to be the one of the car-component with a link to it's issue#   😃
- I think, you should tell the developers to create a new branch and add a test and add storybook and all other little things, developers tend to forget..
