### ISSUE TITLE
Remove car from user profile

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#5]
name: Remove car from user profile

# Value Proposition

**As a** USER
**I have** to be able to remove a car from my profile
**in order to** manage my car stock.

# Description

![Remove car from user profile](https://user-images.githubusercontent.com/10528055/166945002-50c02d30-ff82-4f86-8399-96eae7e73304.png)

# Acceptance Criteria

- [x] click on "delete"-icon
- [x] open & view "Remove Car from Profile" modal
- [x] if "remove car from profile" is checked and "delete"-button clicked, the car is removed from my profile
- [x] if click on "cancel"-button, the modal is closed and car profile is unchanged

# Tasks

(for developers team)

- [x] create delete function for chosen car profile from local storage
- [x] Modal checkbox "Remove car from profile"
- [x] Modal Button "Delete"
- [x] Modal Button "Cancel"
- [x] Modal Zustand"show / not show"
- [x] delete car profile from user account (!! not db !!)
- [x] add modal with finale delete to delete function

# Complexity
L
