### ISSUE TITLE
Remove Car - Modal

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#6]
name: Remove Car - Modal
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to check "Remove Car from Profile" and click "delete"-button
**in order to** remove car from profile.

# Description

Scribble / design or text

![Remove car from user profile](https://user-images.githubusercontent.com/10528055/167599382-7e7eae39-2761-4063-b4b2-554f1a1069e4.png)

- [ ] View option before final removal of car from profile

# Tasks

(for developers team)

- [ ] Modal checkbox "Remove car from profile"
- [ ] Modal Button "Delete"
- [ ] Modal Button "Cancel"
- [ ] Modal UseState "show / not show"

# Complexity
S
