### ISSUE TITLE
 Connect to API to fetch car details

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#7]
name:  Connect to DAT API
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to automatically retrieve a vehicle's built setup
**in order to** all info available.

# Description

Connect to third party API to fetch car details via "VIN" request
import car info into db and connect to vin
! VIN = unique identifier !

# Acceptance Criteria

- [x] when I add a new car and enter the vin, I want to retrieve all car details from API automatically within my car's detail page

# Tasks

(for developers team)

- [x] setup FETCH API request/call
- [x] GET request based on VIN and API key
- [ ] POST retrieved data to mongodb under cars category
- [ ] match carprofile in db to userprofile

# Complexity
L
