### ISSUE TITLE
Car Details Page

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#8]
name: Car Details Page

# Value Proposition

**As a** USER
**I have** to be able to view a car's details on a car details page
**in order to** view the details and access the services offered.

# Description

![Car Details Page](https://user-images.githubusercontent.com/10528055/167110246-133a972a-be7e-4f8f-96cd-e61e53c4847d.png)

# Acceptance Criteria

- [x] Accessible car details page from car profile card
- [x] Image Slider with full screen image display when click on image
- [x] Service Navigation
- [x] Service Navigation --> Upload vehicle images
- [x] List of car details retrieved from VIN identification
- [x] History list --> display uploaded files
- [x] History --> add new files to history list

# Tasks

(for developers team)

- [x] Create/reuse component image slider
- [x] fetch data from API / db based on VIN identification
- [x] post data (imgs / documents) to cloudinary db on upload

# Complexity
XL
