### ISSUE TITLE
Car Details Page - Share Car Profile

### ISSUE THREAD

**Issue by sebastianottow** [StelzenPieper/capstone-project#9]
name: Car Details Page - Share Car Profile
about: 
title: ''
labels: ''
assignees: ''

# Value Proposition

**As a** USER
**I have** to be able to share my car's profile
**in order to** hand over information to workshops, friends, future buyers.

# Description

Item in the Service Nav
![Car Details Page](https://user-images.githubusercontent.com/10528055/167119993-fdf62283-10ee-473f-aa1d-c298a486ac8c.png)

# Acceptance Criteria

- [ ] generates a Link to car profile 
- [ ] link is copied into clipboard automatically
- [ ] (if possible) generate car specific QR-Code with generated link behind it

# Tasks

(for developers team)

- [ ] generate unique link to profile page
- [ ] function to auto-fill link to clipboard
- [ ] generate QR-Code for link

# Complexity
M
